# Generated by Django 4.2.18 on 2025-02-04 10:50

import core.datetimes.ad_datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0008_alter_psql_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='pending_amount',
            field=models.DecimalField(db_column='PendingAmount', decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='premium',
            name='created_date',
            field=models.DateTimeField(db_column='CreatedDate', default=core.datetimes.ad_datetime.AdDatetime.now),
        ),
    ]
