# Generated by Django 4.2.23 on 2025-08-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0009_added_pending_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='payment_status',
            field=models.CharField(db_column='PaymentStatus', default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='premium',
            name='rowid',
            field=models.TextField(blank=True, db_column='RowID', null=True),
        ),
    ]
